language: java


before_script:
  - export MAVEN_SKIP_RC=true
  - export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=192m"
  - unset GEM_PATH GEM_HOME IRBRC JRUBY_OPTS
  - "export PATH=`pwd`/bin:$PATH"
  - echo $HOME

jdk:
  - oraclejdk8